//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGetUsuario.UsuariosServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosServiceReference.IUsuariosService")]
    public interface IUsuariosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuariosResponse")]
        ProxyServices.Dto.Usuarios[] ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios[]> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/InsertarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/InsertarUsuarioResponse")]
        ProxyServices.Dto.Usuarios InsertarUsuario(ProxyServices.Dto.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/InsertarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/InsertarUsuarioResponse")]
        System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios> InsertarUsuarioAsync(ProxyServices.Dto.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ModificarUsuarioResponse")]
        ProxyServices.Dto.Usuarios ModificarUsuario(ProxyServices.Dto.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios> ModificarUsuarioAsync(ProxyServices.Dto.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/EliminarUsuarioResponse")]
        ProxyServices.Dto.Usuarios EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuariosService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios> EliminarUsuarioAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosServiceChannel : PruebaGetUsuario.UsuariosServiceReference.IUsuariosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosServiceClient : System.ServiceModel.ClientBase<PruebaGetUsuario.UsuariosServiceReference.IUsuariosService>, PruebaGetUsuario.UsuariosServiceReference.IUsuariosService {
        
        public UsuariosServiceClient() {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProxyServices.Dto.Usuarios[] ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios[]> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public ProxyServices.Dto.Usuarios InsertarUsuario(ProxyServices.Dto.Usuarios usuario) {
            return base.Channel.InsertarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios> InsertarUsuarioAsync(ProxyServices.Dto.Usuarios usuario) {
            return base.Channel.InsertarUsuarioAsync(usuario);
        }
        
        public ProxyServices.Dto.Usuarios ModificarUsuario(ProxyServices.Dto.Usuarios usuario) {
            return base.Channel.ModificarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios> ModificarUsuarioAsync(ProxyServices.Dto.Usuarios usuario) {
            return base.Channel.ModificarUsuarioAsync(usuario);
        }
        
        public ProxyServices.Dto.Usuarios EliminarUsuario(int id) {
            return base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task<ProxyServices.Dto.Usuarios> EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
    }
}
